title: Portfolio | brianholt.ca
email: bholtbholt@icloud
description: >
  I'm a full stack software developer who's heckin good at the front-end. I'm not the Brian Holt at Microsoft. My background includes working on large Ruby on Rails apps, and teaching User Experience design. Need a website built? Too bad, I'm busy.
url: https://www.brianholt.ca
twitter: https://twitter.com/BHOLTBHOLT
github: https://github.com/bholtbholt
medium: https://medium.com/@bholtbholt
linkedin: https://linkedin.com/in/bholtbholt

form:
  action: https://2vauwh7ky0.execute-api.us-east-1.amazonaws.com/dev/static-site-mailer
  ses_email: staticsitecontactform@gmail.com
  send_to_email: bholtbholt@icloud.com

port: 3000

sass:
  style: compressed

collections:
  - now

permalink: /:categories/:title/

defaults:
  - scope:
      type: posts
    values:
      layout: post
