# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Portfolio | brianholt.ca
email: bholtbholt@icloud
description: >
  The portfolio of Brian Holt: award-winning graphic designer, web developer, artist, musician, and living person.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brianholt.ca" # the base hostname & protocol for your site
twitter_username: bholtbholt
github_username:  bholtbholt

# Build settings
markdown: kramdown

gems: [jekyll-autoprefixer]
