title: Portfolio | brianholt.ca
email: bholtbholt@icloud
description: >
  Brian Holt is a front-end developer living in Vancouver, Canada, focused on scalable design systems. His background includes working on large Ruby on Rails apps with React + Redux front-ends and teaching User Experience design. Currently, he’s infatuated with Elm and functional programming, TypeScript, and Serverless. And he’s always in search of tacos and bourbon sours.
url: https://www.brianholt.ca
twitter: https://twitter.com/BHOLTBHOLT
github: https://github.com/bholtbholt
medium: https://medium.com/@bholtbholt
linkedin: https://linkedin.com/in/bholtbholt

form:
  action: https://2vauwh7ky0.execute-api.us-east-1.amazonaws.com/dev/static-site-mailer
  ses_email: staticsitecontactform@gmail.com
  send_to_email: bholtbholt@icloud.com

source: src
port: 3000

collections:
  - now

permalink: /:categories/:title/

defaults:
  - scope:
      type: posts
    values:
      layout: post
