title: Portfolio | brianholt.ca
email: bholtbholt@icloud
description: >
  I'm a senior software engineer who's heckin good at the front-end. I'm not the Brian Holt from Frontend Masters. My background includes work on JavaScript frameworks like React and Svelte, large Ruby on Rails apps, and teaching User Experience design.
url: https://www.brianholt.ca
github: https://github.com/bholtbholt
linkedin: https://linkedin.com/in/bholtbholt

form:
  action: https://formsubmit.co/c168c951e89fffaf972dbecd9fa5e4c1

port: 3000

sass:
  style: compressed

collections:
  - now

permalink: /:categories/:title/

defaults:
  - scope:
      type: posts
    values:
      layout: post
