<article>
<h1>Who is Brian Holt?</h1>
<section>
<p>I applied for a design scholarship that was solely based upon the contents of a little black book. Inside, participants needed to explain why they deserved to win, showcase their work, and write a little bit about themselves. <em>And have it completed in two weeks.</em> Since all the applicants were relatively unknown and early into their design careers (myself included) I found it amusing to play up the anonymity of the submissions. Who were these people anyway? Why did they matter? In addition, it struck me that the judges would be reading nearly identical books; they'd see high-quality work, a compelling argument, and some personality. In that case, making something as trivial as a name the focus was bound to stand out.</p>
<p>In order to inflate my name to ridiculous stature, I borrowed famous characters, people, and historical events and twisted their purpose. What if, instead of travelling to the moon to beat the Soviet Union, the Americans travelled there hoping to find the answer to a great question: who is Brian Holt? Or if Super Mario was on a quest to learn an answer rather than save the princess? Or if Muhammad Ali fought Sonny Lester for information instead of the Heavyweight Championship? Yeah, <em>ridiculous.</em></p>
<p>But borrowing characters and superimposing "Who is Brian Holt?" to posters wasn't enough. The judges wouldn't understand the struggles and importance of these altered historical events if they were constrained to a little black book. I needed the judges to wonder for themselves. The effect needed to transcend the book. So I printed up more than 60 posters and plastered the small office entrance with them. The posters lead up to the front doors, where on the ground in large letters was the phrase "WHO IS BRIAN HOLT?".</p>
<p>A week later, the black book arrived at the office in the mail, wrapped in one of the posters. It began with a tongue-in-cheek foreward citing many of life's vast questions which all lead to the most important of all: who is Brian Holt. The following pages included a poster asking "Who is Brian Holt?", followed by a single sentence answering with a value I held, a piece of work that demonstrated the value, then an explanation. In ten sentences I described values that defined me as a person and designer. Unfortunately, I didn't win the scholarship, but the judges probably know my name. Or at least both them and the janitors know who vandalized the building.</p></section>
<aside><div class="left">
	<a href="images/WhoIsBrianHolt1.jpg" class="fancybox" title="Muhammad Ali fights Sonny Lester for an answer" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt1-thumb.jpg" width="118" height="100"></a>
    <a href="images/WhoIsBrianHolt2.jpg" class="fancybox" title="An answer was what Americans hoped to find on the moon" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt2-thumb.jpg" width="118" height="100"></a>
    <a href="images/WhoIsBrianHolt3.jpg" class="fancybox" title="The phrase that shook the world in Ayn Rand's magnum opus, Atlas Shrugged" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt3-thumb.jpg" width="118" height="100"></a>
    <a href="images/WhoIsBrianHolt4.jpg" class="fancybox" title="Carl Sagan's reason for travelling throughout the Cosmos" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt4-thumb.jpg" width="118" height="100"></a>
    <a href="images/WhoIsBrianHolt5.jpg" class="fancybox" title="A straight answer is all Clint Eastwood wants" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt5-thumb.jpg" width="118" height="100"></a>
    <a href="images/WhoIsBrianHolt6.jpg" class="fancybox" title="Even Roy Lichtenstein thought the search for the answer was Hopeless" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt6-thumb.jpg" width="118" height="100"></a>
    <a href="images/WhoIsBrianHolt7.jpg" class="fancybox" title="A life-long investigation for Tintin and Snowy" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt7-thumb.jpg" width="118" height="100"></a>
    <a href="images/WhoIsBrianHolt8.jpg" class="fancybox" title="Since the princess was kidnapped more often than not, Mario pursued more pressing matters" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt8-thumb.jpg" width="118" height="100"></a>
    <a href="images/WhoIsBrianHolt9.jpg" class="fancybox" title="The reason Jack Torrance went mad" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt9-thumb.jpg" width="118" height="100"></a>
    <a href="images/WhoIsBrianHolt10.jpg" class="fancybox" title="What Dr. Alan Grant really hoped to uncover during one of his digs" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt10-thumb.jpg" width="118" height="100"></a>
    <a href="images/WhoIsBrianHolt11.jpg" class="fancybox" title="Obviously, the correct answer to Alex Trebek's trivia" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt11-thumb.jpg" width="118" height="100"></a>
    <a href="images/WhoIsBrianHolt12.jpg" class="fancybox" title="Ask not what your country can do for you – ask who is Brian Holt" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt12-thumb.jpg" width="118" height="100"></a>
    <a href="images/WhoIsBrianHolt13.jpg" class="fancybox" title="Wondered more often than 'who is Heisenberg?'" rel="Who Is Brian Holt"><img src="images/WhoIsBrianHolt13-thumb.jpg" width="118" height="100"></a>
</div></aside>
</article>
<div class="clear"></div>